spring:
  application:
    name: tour-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/tourdb
    username: tour
    password: tour
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tour

tour:
  app:
    service-name: tour-backend
    version: 0.0.1-SNAPSHOT
  security:
    cors:
      allowed-origins:
        - http://localhost:5173

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

